### PR TITLE
Adds support for user images as a background.

### PR DESCRIPTION
**Pull request by Flat**
Images need to be in .bgr bin format. This can be accomplished with image magick using the convert command and then rotating the image 90 degrees.

ex:

```
convert yourimg.png -channel B -separate yourimg.png -channel G -separate yourimg.png -channel R -separate -channel RGB -combine -rotate 90 yourimg.rgb
```

then simply rename .rgb to .bin and place it on your sdcard and edit your config to the path of the image.

### CODE REVIEW

**Comment by Cpasjuste** [comment]
Hi Flat,

Thanks for this, this is good idea. Tought i think you should load the image data once in the configuration loading code, this would prevent it to be loaded each time a menu is drawn. You could allocate it in the config struct for example.

 I'll merge your commit as soon as you do that :)

**Comment by Flat** [comment]
Hi @Cpasjuste I refactored the code so it should only load once now. However I'm having an issue with menu_more. Any ideas why it might not be loading the images for that menu?

**Comment by Flat** [comment]
Hi @Cpasjuste,
The code should be a lot cleaner now and load the image only once. It should also use the images on every menu for a consistent design. I've also fixed a couple menus where the border size wasn't the same. :)

**Comment by Cpasjuste** [comment]
Hi Flat,

Thanks for this, I think people will like it. I'll try to take a look tomorrow then merge :)

**Comment by Flat** [comment]
Hey no problem. Hopefully people find it useful!

**Pull request merged**
