### PR TITLE
Updated to compile with ctrulib-1.0

### PR DESCRIPTION
**Pull request by gemarcano**
Also added a Readme with some instructions and credits.

### CODE REVIEW

**Comment by gemarcano** [comment]
As far as I can tell, this seems to work. I was able to compile and load it on my o3DS.

**Comment by Cpasjuste** [comment]
Hi gemarcano, First thanks for taking the time to make a pull request. 

I did also port CtrBootManager to latest ctrulib and CakeBrah a few days ago, but i'm unable to get CakeBrah to load a payload since then. This prevent loading arm9 payload (bin, dat..) which is one of the first goal of this application. Can you confirm this with your changes ?

Thanks,
David.

**Comment by gemarcano** [comment]
I can try. I'll let you know whether or not my version succeeds.

**Comment by gemarcano** [comment]
I haven't been able to launch something via CakeHax in neither the old or new version. To launch it, do I need to do anything special other than select the Launcher.dat from the browser? I tried to launch Decrypt9 as found [here](https://builds.archshift.com/decrypt9/nightly/).

**Comment by gemarcano** [comment]
I've tried with EmuNAND9's own EmuNAND9.dat as well, with no success on neither the new or old versions. I read somewhere something about MSET-- I need to downgrade it (I really don't want to keep messing with my sysNAND, which is at 9.2).

**Comment by gemarcano** [comment]
I can't boot anything that's not a .3dsx file (no .dat for MSET reasons, and no .bin for unknown reasons) in either the new OR the old version (1.2 as found [here](https://gbatemp.net/threads/ctrbootmanager-3ds-boot-manager-loader-homemenuhax.398383/)).

Using Brahma II directly from its 3dsx, I can boot the .bins in question.

When I try to boot a .bin, the screen is wiped black, but nothing happens (this happens on both the old and new version).

**Comment by gemarcano** [comment]
I take back what I said about .bin files. I may not be able to load EmuNAND9.bin from the file browser, but I can sure boot code.bin from EmuNAND9. I'm not 100% sure why I can boot one and not the other (I know rxTools has an offset specified in the config file).

**Comment by Cpasjuste** [comment]
Hi gemarcano,

I finally done/fixed this the "bad way" by using an old ctrulib commit. By the way, thanks to you i did take the time to add needed dependencies as submodules.

I'm still interested by your "readme" commit, if you have the time to make a pull request for this :+1:  

Thanks again,
David.

**Pull request closed without merging**
